on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access variables
        run: |
          echo "Environment: $APP_ENV"
      - name: Use Secret in command
        run: |
          echo "Connecting to database"
          echo "docker run -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} my-database-image"
